name: deploy staging 🛫🧪

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x.x
          cache: yarn
      - run: yarn --immutable
      - run: yarn lint
      - run: yarn lint:types
      - run: yarn test
  deploy:
    needs: lint
    runs-on: ubuntu-latest
    concurrency:
      group: staging
      cancel-in-progress: true
    steps:
      - name: SSH Command
        uses: appleboy/ssh-action@v1.0.3
        with:
          # hostname | IP of the server
          host: ${{ secrets.STAGING_SSH_HOST }}
          username: ${{ secrets.STAGING_SSH_USERNAME }}
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          proxy_fingerprint: ${{ secrets.STAGING_SSH_FINGERPRINT }}
          script: source ~/.nvm/nvm.sh; ~/deploy.sh
